# Script file for scomm
# testscript.sc
#
# SetDelaySeconds(), SetDelayMilliseconds(), and SetDelayMicroseconds() all accept a single
# parameter, and will delay for the amount of provided time

# The Write() command takes a single quotation mark delimited string that wil be written to the
# connected serial port

# Any line began with a pound sign will be ignored

# Any line that has invalid syntax will be ignored, and a warning will be output to stdout

DelayMilliseconds(500)
Write("{ptchange:2:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:3:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:4:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:5:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:6:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:7:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:8:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
Write("{ptchange:9:dout}")
DelayMilliseconds(250)
Read()
DelayMilliseconds(250)
FlushRXTX()

Loop() {
    Write("{dwrite:2:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:3:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:4:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:5:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:6:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:7:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:8:1}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    FlushRXTX()

    Write("{dwrite:2:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:3:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:4:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:5:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:6:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:7:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    Write("{dwrite:8:0}")
    DelayMilliseconds(250)
    Read()
    DelayMilliseconds(250)
    FlushRXTX()
}