#ifndef QSERIALTERMINAL_QSERIALTERMINALSTRINGS_H
#define QSERIALTERMINAL_QSERIALTERMINALSTRINGS_H


namespace QSerialTerminalStrings
{
    extern const char *QUIT_PROMPT_STRING;
    extern const char *QUIT_PROMPT_WINDOW_TITLE_STRING;
    extern const char *INVALID_SETTINGS_DETECTED_STRING;
    extern const char *INVALID_SETTINGS_DETECTED_WINDOW_TITLE_STRING;
    extern const char *MAIN_WINDOW_TITLE;
    extern const char *SETTINGS_DIALOG_WINDOW_TITLE;
    extern const char *SUCCESSFULLY_OPENED_SERIAL_PORT_STRING;
    extern const char *MAIN_WINDOW_STYLESHEET;
}


#endif //QSERIALTERMINAL_QSERIALTERMINALSTRINGS_H
